/**
 * Live production validation, from a shell.
 *
 * Runs the same checks the /validation/live-qbo page runs and writes
 * docs/LIVE_VALIDATION.md. Read-only against QuickBooks throughout.
 *
 * Usage:
 *   npm run validate:live
 *   npm run validate:live -- --period 2026-07 --months 24
 *   npm run validate:live -- --company <uuid> --json validation.json
 *
 * Exits 1 when the production gate does not pass, so CI can depend on it.
 */
import { writeFileSync } from 'node:fs';
import { getPool, queryOne } from '../src/lib/db/pool';
import { runLiveValidation } from '../src/lib/validation/run';
import { monthPeriodOf } from '../src/lib/util/dates';
import type { CheckStatus, ValidationRun } from '../src/lib/validation/types';

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const ICON: Record<CheckStatus, string> = {
  PASS: '  ok  ',
  FAIL: ' FAIL ',
  NOT_AVAILABLE: '  n/a ',
  NEEDS_REVIEW: ' review',
};

function render(run: ValidationRun): string[] {
  const lines: string[] = [];
  lines.push('# Live QuickBooks validation');
  lines.push('');
  lines.push('Generated by `npm run validate:live`. Every QuickBooks call in this run was a');
  lines.push('GET; the only writes were to this application\'s own database.');
  lines.push('');
  lines.push('| | |');
  lines.push('| --- | --- |');
  lines.push(`| Company | ${run.company.quickbooksName ?? run.company.localName} |`);
  lines.push(`| Realm | ${run.company.realmId ?? '—'} |`);
  lines.push(`| Environment | ${run.environment} |`);
  lines.push(`| Validation month | ${run.period?.label ?? '—'} |`);
  lines.push(`| Reporting basis | ${run.period ? `${run.period.accountingMethod} Basis` : '—'} |`);
  lines.push(`| As-of date | ${run.period?.asOfDate ?? '—'} |`);
  lines.push(`| Report confidence | ${run.confidenceScore === null ? '—' : `${run.confidenceScore}/100`} |`);
  lines.push(`| App version | ${run.appVersion} |`);
  lines.push(`| Generated | ${run.generatedAt} |`);
  lines.push('');

  if (run.fatal) {
    lines.push('> **The run stopped early.** ' + run.fatal);
    lines.push('');
  }

  lines.push(`## Production Ready: ${run.productionReady ? 'YES' : 'NO'}`);
  lines.push('');
  lines.push('| Gate criterion | Status | Blocker |');
  lines.push('| --- | --- | --- |');
  for (const g of run.gate) {
    lines.push(`| ${g.label} | ${g.status.replace('_', ' ')} | ${(g.blocker ?? '—').replace(/\|/g, '\\|')} |`);
  }
  lines.push('');

  for (const section of run.sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    if (section.note) {
      lines.push(`> ${section.note}`);
      lines.push('');
    }
    lines.push('| Check | Status | Detail |');
    lines.push('| --- | --- | --- |');
    for (const c of section.checks) {
      const detail = `${c.detail}${c.remedy ? ` **${c.remedy}**` : ''}`.replace(/\|/g, '\\|');
      lines.push(`| ${c.name} | ${c.status.replace('_', ' ')} | ${detail} |`);
    }
    lines.push('');
    for (const table of section.tables ?? []) {
      lines.push(`### ${table.title}`);
      lines.push('');
      lines.push(`| ${table.columns.join(' | ')} |`);
      lines.push(`| ${table.columns.map(() => '---').join(' | ')} |`);
      for (const row of table.rows) {
        lines.push(`| ${row.cells.map((c) => c.replace(/\|/g, '\\|')).join(' | ')} |`);
      }
      lines.push('');
      if (table.caption) {
        lines.push(table.caption);
        lines.push('');
      }
    }
  }

  return lines;
}

async function main(): Promise<void> {
  let companyId = arg('company');
  if (!companyId) {
    const row = await queryOne<{ id: string }>(
      'SELECT id FROM companies WHERE is_demo = FALSE ORDER BY created_at LIMIT 1',
    );
    companyId = row?.id;
  }
  if (!companyId) {
    throw new Error('No non-demo company found. Connect QuickBooks first — see docs/INTUIT_PRODUCTION_SETUP.md.');
  }

  const owner = await queryOne<{ owner_user_id: string }>(
    'SELECT owner_user_id FROM companies WHERE id = $1',
    [companyId],
  );
  if (!owner) throw new Error('Company not found.');

  const periodArg = arg('period');
  const monthsArg = arg('months');

  const run = await runLiveValidation({
    companyId,
    userId: owner.owner_user_id,
    ...(periodArg ? { period: monthPeriodOf(`${periodArg}-01`) } : {}),
    ...(monthsArg ? { historyMonths: Number(monthsArg) } : {}),
    ...(process.argv.includes('--skip-import') ? { skipImport: true } : {}),
  });

  console.log('');
  for (const section of run.sections) {
    console.log(`— ${section.title}`);
    for (const c of section.checks) {
      console.log(`[${ICON[c.status]}] ${c.name}`);
      console.log(`          ${c.detail}`);
      if (c.remedy) console.log(`          -> ${c.remedy}`);
    }
    console.log('');
  }

  console.log('='.repeat(72));
  console.log(`Production Ready: ${run.productionReady ? 'YES' : 'NO'}`);
  if (run.blockers.length > 0) {
    console.log('');
    console.log('Blockers:');
    for (const b of run.blockers) console.log(`  - ${b}`);
  }
  console.log('');

  const out = arg('markdown') ?? 'docs/LIVE_VALIDATION.md';
  writeFileSync(out, render(run).join(String.fromCharCode(10)) + String.fromCharCode(10), 'utf8');
  console.log(`Wrote ${out}`);

  const json = arg('json');
  if (json) {
    writeFileSync(json, JSON.stringify(run, null, 2), 'utf8');
    console.log(`Wrote ${json}`);
  }

  await getPool().end();
  if (!run.productionReady) process.exit(1);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack : err);
  process.exit(1);
});
